apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: quay.io/maryemaloui/backend-chatbot:latest
        env:
          - name: mongo_url
            value: mongodb://mongodb-service:27017/backend
        ports:
        - containerPort: 80
