apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend-sa
      containers:
        - name: frontend
          image: maryemaloui/frontend-chatbot:latest
          ports:
            - containerPort: 3001
          env:
          - name: urladmin
            value: http://backend.apps-crc.testing/admins
          - name: urlchat
            value: http://backend.apps-crc.testing/chats
          - name: urlcertif
            value: http://backend.apps-crc.testing/certifs
          - name: socketUrl
            value: http://rasa.apps-crc.testing:5005
          volumeMounts:
            - name: frontend-data
              mountPath: /usr/share/nginx/html
      volumes:
        - name: frontend-data
          persistentVolumeClaim:
            claimName: frontend-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001