apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa
  labels:
    app: rasa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasa
  template:
    metadata:
      labels:
        app: rasa
    spec:
      containers:
      - name: rasa
        image: maryemaloui/rasa-chatbot:latest
        ports:
        - containerPort: 5005
---
apiVersion: v1
kind: Service
metadata:
  name: rasa
spec:
  selector:
    app: rasa
  ports:
    - protocol: TCP
      port: 5005  
      targetPort: 5005
