apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend-sa
      containers:
        - name: frontend
          image: maryemaloui/frontend-chatbot:latest
          imagePullPolicy: Always  
          ports:
            - containerPort: 80
          env:
          - name: urladmin
            value: http://backend.apps-crc.testing/admins
          - name: urlchat
            value: http://backend.apps-crc.testing/chats
          - name: urlcertif
            value: http://backend.apps-crc.testing/certifs
          - name: socketUrl
            value: http://rasa.apps-crc.testing
          volumeMounts:
            - name: frontend-storage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: frontend-storage
          persistentVolumeClaim:
            claimName: frontend-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80